import { ArrowLeftIcon } from '@heroicons/react/24/solid';
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore';
import { AnimatePresence, motion } from 'framer-motion';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Comment from '../../components/Comment';
import CommentModal from '../../components/CommentModal';
import Loading from '../../components/Loading';
import Post from '../../components/Post';
import Sidebar from '../../components/Sidebar';
import Widgets from '../../components/Widgets';
import { db } from '../../firebase';

const Posts = ({ news, followers }) => {
  const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState('');
  const [comments, setComments] = useState([]);

  //get the post data
  useEffect(() => {
    return onSnapshot(doc(db, 'posts', id), (snapshot) => setPost(snapshot));
  }, [db, id]);
  // get comments data
  useEffect(() => {
    return onSnapshot(query(collection(db, 'posts', id, 'comments'), orderBy('timestamps', 'desc')), (snapshot) => setComments(snapshot.docs));
  }, [db, id]);
  return (
    <div>
      <>
        <Head>
          <title>Posts page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen mx-auto max-w-[90rem]">
          {/* Sidebar */}
          <Sidebar />
          {/* Feed */}
          <div className="xl:ml-[370px] border-x border-gray-200 xl:min-w-[576px] flex-grow max-w-xl sm:ml-[73px]">
            <div className="flex items-center py-2 px-3 sticky top-0 z-50 bg-white/80 backdrop-blur-md border-gray-200">
              <div onClick={() => router.push('/')} className=" flex h-9 w-9 mr-2 md:!p-0  items-center justify-center hover-effect">
                <ArrowLeftIcon className="!h-5 text-lg" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold cursor-pointer">Tweet</h2>
            </div>
            <AnimatePresence>
              {post ? (
                <>
                  <motion.div key={id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5, delay: 1 }}>
                    <Post post={post} id={id} />
                    <AnimatePresence>
                      {comments.length > 0 &&
                        comments.map((comment) => (
                          <motion.div key={comment.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1 }} exit={{ opacity: 0 }}>
                            <Comment comments={comment?.data()} key={comment.id} originalPostId={id} commentId={comment.id} />
                          </motion.div>
                        ))}
                    </AnimatePresence>
                  </motion.div>
                </>
              ) : (
                <motion.div key={post.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1 }} exit={{ opacity: 0 }}>
                  <Loading />
                </motion.div>
              )}
            </AnimatePresence>
          </div>
          {/* Widgets */}
          <Widgets news={news?.articles} followers={followers.results} />
          {/* Modal */}
          <CommentModal />
        </main>
      </>
    </div>
  );
};
export default Posts;

export const getServerSideProps = async (context) => {
  const news = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/health/us.json').then((res) => res.json());
  // Who to follow section
  const followers = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture').then((res) => res.json());
  return {
    props: {
      news,
      followers,
    },
  };
};
