import Head from 'next/head';
import { useRouter } from 'next/router';
import CommentModal from '../components/CommentModal';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home({ news, followers }) {
  return (
    <>
      <Head>
        <title>Twitter Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto max-w-[90rem]">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets news={news?.articles} followers={followers.results} />
        {/* Modal */}
        <CommentModal />
      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
export const getServerSideProps = async (context) => {
  const news = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/health/us.json').then((res) => res.json());
  // Who to follow section
  const followers = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture').then((res) => res.json());
  return {
    props: {
      news,
      followers,
    },
  };
};
